
package observerpattern;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.text.DateFormatSymbols;

public class MainWeather extends javax.swing.JFrame {

    DateFormatSymbols symbols = new DateFormatSymbols();
    Date date = new Date();
    DateFormat full = new SimpleDateFormat("MMMM dd, yyyy");
    DateFormat time = new SimpleDateFormat("HH:mm");
    
    public MainWeather() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SubscribeButton = new javax.swing.JButton();
        MondayButton = new javax.swing.JButton();
        TuesdayButton = new javax.swing.JButton();
        WednesdayButton = new javax.swing.JButton();
        Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("NAME:");

        SubscribeButton.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        SubscribeButton.setForeground(new java.awt.Color(255, 0, 51));
        SubscribeButton.setText("SUBSCRIBE");
        SubscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubscribeButtonActionPerformed(evt);
            }
        });

        MondayButton.setText("Monday");
        MondayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MondayButtonActionPerformed(evt);
            }
        });

        TuesdayButton.setText("Tuesday");
        TuesdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayButtonActionPerformed(evt);
            }
        });

        WednesdayButton.setText("Wednesday");
        WednesdayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MondayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TuesdayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WednesdayButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(SubscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MondayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TuesdayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WednesdayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubscribeButtonActionPerformed
        MainWeather s = new MainWeather();
        s.setVisible(true);
        s.setTitle(this.Name.getText());
        
    }//GEN-LAST:event_SubscribeButtonActionPerformed

    private void MondayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MondayButtonActionPerformed
        // TODO add your handling code here:
        Monday m = new Monday();
        m.setVisible(true);
        
        WeatherTopic topic = new WeatherTopic();
        
        WeatherObserver a = new WeatherTopicSubscriber(this.Name.getText());
        topic.attach(a);
        a.setSubject(topic);
        
        m.setTitle("Monday's weather is " + full.format(date));
        m.Time.setText(time.format(date));
        m.WeatherInfo.setText(topic.sendMessage("\n Humidity: 80%     40% chance of rain"));
        
    }//GEN-LAST:event_MondayButtonActionPerformed

    private void TuesdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayButtonActionPerformed
        // TODO add your handling code here:
        Tuesday t = new Tuesday();
        t.setVisible(true);
        
        WeatherTopic topic = new WeatherTopic();
        
        WeatherObserver b = new WeatherTopicSubscriber(this.Name.getText());
        topic.attach(b);
        b.setSubject(topic);
        
        t.setTitle("Tuesday's weather is " + full.format(date));
        t.Time.setText(time.format(date));
        t.WeatherInfo.setText(topic.sendMessage("\n Humidity: 60%     15% chance of rain"));
    }//GEN-LAST:event_TuesdayButtonActionPerformed

    private void WednesdayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayButtonActionPerformed
        // TODO add your handling code here:
        Wednesday w = new Wednesday();
        w.setVisible(true);
        
        WeatherTopic topic = new WeatherTopic();
        
        WeatherObserver c = new WeatherTopicSubscriber(this.Name.getText());
        topic.attach(c);
        c.setSubject(topic);
        
        w.setTitle("Wednesday's weather is " + full.format(date));
        w.Time.setText(time.format(date));
        w.WeatherInfo.setText(topic.sendMessage("\n Humidity: 30%     0% chance of rain"));
    }//GEN-LAST:event_WednesdayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWeather.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWeather().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MondayButton;
    private javax.swing.JTextField Name;
    private javax.swing.JButton SubscribeButton;
    private javax.swing.JButton TuesdayButton;
    private javax.swing.JButton WednesdayButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
